import type { Metadata } from 'next'
import { flex, grid } from '../../styled-system/patterns'
import './globals.css'

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="ja">
      <body suppressHydrationWarning={true}>
        <div
          className={grid({
            columns: 1,
            gridTemplateRows: 'auto min-content',
            gap: '0',
            minHeight: '100dvh',
          })}
        >
          <main
            className={flex({
              direction: 'column',
              flex: '1 0 100%',
            })}
          >
            {children}
          </main>
          <footer
            className={flex({
              justify: 'center',
              align: 'center',
              backgroundColor: 'catDark',
              color: 'white',
              padding: '4px 18px',
            })}
          >
            <small>Code for CAT at Ishinomakihack2023</small>
          </footer>
        </div>
      </body>
    </html>
  )
}
